@startuml
class Engine {
  std::string type
  int horsepower
  void start()
}

class Vehicle {
  std::string brand
  int year
}

class Car {
  int doors
  void drive()
}

class Truck {
  double loadCapacity
  void drive()
}

class Garage {
  Garage garage
  delete carEngine
  delete truckEngine
  delete car
  delete truck
  return 0
  void addVehicle()
  void showVehicles()
}

Vehicle <|-- Car
Vehicle <|-- Truck
Garage *-- Garage
@enduml